#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
SWEEP_LAUNCHER="${PROJECT_DIR}/exp/eval_trainable_snn_block_sweep.sh"

export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1}"
export NPROC_PER_NODE="${NPROC_PER_NODE:-2}"
export MASTER_PORT="${MASTER_PORT:-29515}"

export MIN_BLOCKS="${MIN_BLOCKS:-1}"
export MAX_BLOCKS="${MAX_BLOCKS:-24}"
export SNN_TIMESTEPS="${SNN_TIMESTEPS:-4}"
export SNN_SPIKE_POSITION="${SNN_SPIKE_POSITION:-post}"
export SNN_SPIKE_PATCH="${SNN_SPIKE_PATCH:-0}"

export SWEEP_EPOCHS="${SWEEP_EPOCHS:-1}"
export SWEEP_DISTILL_WEIGHT="${SWEEP_DISTILL_WEIGHT:-0.7}"
export SWEEP_DUMP_MODEL_SUMMARY="${SWEEP_DUMP_MODEL_SUMMARY:-1}"
export SWEEP_SKIP_INITIAL_BEST_CHECKPOINT="${SWEEP_SKIP_INITIAL_BEST_CHECKPOINT:-1}"
export SWEEP_TAG="${SWEEP_TAG:-1epoch_ddp_$(date +%Y%m%d_%H%M%S)}"

export BATCH_SIZE="${BATCH_SIZE:-1}"
export UPDATE_FREQ="${UPDATE_FREQ:-1}"
export LR="${LR:-2e-5}"
export WARMUP_EPOCHS="${WARMUP_EPOCHS:-1}"
export CUDNN_BENCHMARK="${CUDNN_BENCHMARK:-0}"

echo "Trainable SNN block sweep, one epoch, DDP"
echo "CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}"
echo "NPROC_PER_NODE=${NPROC_PER_NODE}"
echo "MIN_BLOCKS=${MIN_BLOCKS}"
echo "MAX_BLOCKS=${MAX_BLOCKS}"
echo "SNN_TIMESTEPS=${SNN_TIMESTEPS}"
echo "SNN_SPIKE_POSITION=${SNN_SPIKE_POSITION}"
echo "SNN_SPIKE_PATCH=${SNN_SPIKE_PATCH}"
echo "SWEEP_EPOCHS=${SWEEP_EPOCHS}"
echo "SWEEP_DISTILL_WEIGHT=${SWEEP_DISTILL_WEIGHT}"
echo "SWEEP_DUMP_MODEL_SUMMARY=${SWEEP_DUMP_MODEL_SUMMARY}"

bash "${SWEEP_LAUNCHER}"
